name: Python CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Si tienes un archivo requirements.txt, descomenta la siguiente línea:
        # pip install -r requirements.txt
        # Si no tienes un archivo requirements.txt, deja la siguiente línea:
        pip install pytest

    - name: Run tests
      run: pytest Gases\ and\ liquids/tests/

